services:
  dev:
    build: .
    image: babyos
    container_name: babyos-dev
    working_dir: /workspace
    volumes:
      - .:/workspace
      - usr-local:/usr/local/

volumes:
  usr-local:
  cargo-target:
